name = "BayesianCrashCourseVAW"
uuid = "7e80d841-511a-44eb-93a4-91d18ba26241"
authors = ["Mauro Werder <mauro3@runbox.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
